/*js files*/ 
import './js/friendsFilter.js';
/*styles files*/ 
import './scss/fonts.css';
import './scss/normalize.css';
import './scss/base.css';
import './scss/header.css';
import './scss/friends.css';
import './scss/button.css';
import './scss/form.css';
import './scss/footer.css';
import './scss/scroll.css';
/*img files*/ 
import './img/friendsFilter.png';
import './img/btn-close.png';
import './img/btn-add.png';
import'./img/btn-delete.png';
import './img/aphex.jpg';
/*html hbs*/ 
import './index.hbs';